// Objective-C API for talking to github.com/EbrahimTahernejad/xray-mobile Go package.
//   gobind -lang=objc github.com/EbrahimTahernejad/xray-mobile
//
// File is generated by gobind. Do not edit.

#ifndef __XRay_H__
#define __XRay_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@protocol XRayLogger;
@class XRayLogger;

@protocol XRayLogger <NSObject>
- (void)logInput:(NSString* _Nullable)s;
@end

FOUNDATION_EXPORT NSString* _Nonnull XRayGetVersion(void);

FOUNDATION_EXPORT BOOL XRayMeasureDelay(NSString* _Nullable url, int64_t* _Nullable ret0_, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL XRayMeasureOutboundDelay(NSString* _Nullable ConfigureFileContent, NSString* _Nullable url, int64_t* _Nullable ret0_, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void XRaySetMemoryLimit(void);

FOUNDATION_EXPORT BOOL XRayStart(NSData* _Nullable config, id<XRayLogger> _Nullable logger, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void XRayStop(void);

@class XRayLogger;

@interface XRayLogger : NSObject <goSeqRefInterface, XRayLogger> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)logInput:(NSString* _Nullable)s;
@end

#endif
