
// Objective-C API for talking to the following Go packages
//
//	github.com/EbrahimTahernejad/xray-mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __XRay_FRAMEWORK_H__
#define __XRay_FRAMEWORK_H__

#include "XRay.objc.h"
#include "Universe.objc.h"

#endif
